### ISSUE TITLE
Clean up Matcher

### ISSUE THREAD

**Issue by SamStudio8** [SAMTOMINDUSTRYS/stex2#6]
* [x] Splits (https://github.com/SAMTOMINDUSTRYS/stex2s-python/commit/096d491a31a00adcf1d59e4d8fd74938e6f32a3f)
* [ ] Orderbook and Matcher should not duplicate work
* [ ] Matcher emits Trade with explicit changes (closed orders, split orders)
* [x] Bring some sanity to the price calculation (https://github.com/SAMTOMINDUSTRYS/stex2s-python/commit/4d8107c41a7327e9d98f4fecac84c4f98d7dd547)
* [x] Push business back to domain logic (https://github.com/SAMTOMINDUSTRYS/stex2s-python/commit/f87b8949ac4c7afeab1db10e452ec6274324839f)
* [ ] Potentially can test `get_execution_price` instead of entire `match_orderbook` stack for T7 suite
